-- Update admin user password (Admin@123!)
-- bcrypt hash cost=11 generated by PasswordHasher tool
UPDATE "Users" 
SET "PasswordHash" = '$2a$11$dOCbTcqbG8jf0HQLyZliD.dXPlq/HDKUZR6DxS1lwSU2d5Vbm7i1m'
WHERE "Email" = 'admin@portfolio.local';

-- Update member user password (Member@123!)
UPDATE "Users" 
SET "PasswordHash" = '$2a$11$GU2dYpR9ARF6Sbyicxz7eOzFzjgQBSyQbhKtpsNU0Nv29HcoI5HDK'
WHERE "Email" = 'member@portfolio.local';

-- Update guest user password (Guest@123!)
UPDATE "Users" 
SET "PasswordHash" = '$2a$11$W64nPR8YLjkNvSMm/n/et.PHRa5S4o3.3xRzQunxzcsYDVv4a8TKG'
WHERE "Email" = 'guest@portfolio.local';
